if (!window.lpcad0701s) { window.lpcad0701s = {}; }

var p; // shortcut to reference prototypes

// stage content:
(window.lpcad0701s.lpc_ad_07_01s = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_1 = function() {
		playSound("GOOD",0);
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(1).call(this.frame_1).wait(1));

	// Warstwa 1
	this.reset = new window.lpcad0701s.btn_reset();
	this.reset.setTransform(681,359,1,1,0,0,0,24,24);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.reset}]}).wait(2));

	// Layer 2
	this.btn6 = new window.lpcad0701s.btn();
	this.btn6.setTransform(462.1,330,0.753,1.788,0,0,0,47.5,37.6);

	this.btn7 = new window.lpcad0701s.btn();
	this.btn7.setTransform(544.3,330,0.564,1.788,0,0,0,47.5,37.6);

	this.btn5 = new window.lpcad0701s.btn();
	this.btn5.setTransform(376.3,330,0.564,1.788,0,0,0,47.5,37.6);

	this.btn4 = new window.lpcad0701s.btn();
	this.btn4.setTransform(235.6,365.7,1.082,0.834,0,0,0,47.5,37.6);

	this.btn3 = new window.lpcad0701s.btn();
	this.btn3.setTransform(118.5,365.7,1.082,0.834,0,0,0,47.6,37.6);

	this.btn2 = new window.lpcad0701s.btn();
	this.btn2.setTransform(305.3,296.5,0.612,0.894,0,0,0,47.5,37.6);

	this.btn1 = new window.lpcad0701s.btn();
	this.btn1.setTransform(221.3,296.5,0.612,0.894,0,0,0,47.5,37.6);

	this.btn0 = new window.lpcad0701s.btn();
	this.btn0.setTransform(122,296.5,0.894,0.894,0,0,0,47.5,37.6);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.btn0},{t:this.btn1},{t:this.btn2},{t:this.btn3},{t:this.btn4},{t:this.btn5},{t:this.btn7},{t:this.btn6}]}).to({state:[]},1).wait(1));

	// Layer 5
	this.pic3 = new window.lpcad0701s.pic4();
	this.pic3.setTransform(180.2,211.2,1.018,1.018,0,0,0,53,14.5);

	this.pic1 = new window.lpcad0701s.pic2();
	this.pic1.setTransform(237.3,180.3,1.018,1.018,0,0,0,26.5,26);

	this.pic4 = new window.lpcad0701s.pic5();
	this.pic4.setTransform(488.4,213.2,1.026,1.026,0,0,0,49,14.5);

	this.pic2 = new window.lpcad0701s.pic3();
	this.pic2.setTransform(563.3,206.9,1.026,1.026,0,0,0,22,18);

	this.pic0 = new window.lpcad0701s.pic1();
	this.pic0.setTransform(517,188.6,1.026,1.026,0,0,0,42.5,27.5);

	this.pic7 = new window.lpcad0701s.pic8();
	this.pic7.setTransform(193.1,117.7,1.018,1.018,0,0,0,21,71.5);

	this.pic6 = new window.lpcad0701s.pic7();
	this.pic6.setTransform(518.7,121.3,1.026,1.026,0,0,0,32,73);

	this.pic5 = new window.lpcad0701s.pic6();
	this.pic5.setTransform(139.2,140.3,1.018,1.018,0,0,0,31,62.5);

	this.mc7 = new window.lpcad0701s.mc8();
	this.mc7.setTransform(544,334.2,1.11,1.11,0,0,0,16,54.5);

	this.mc6 = new window.lpcad0701s.mc7();
	this.mc6.setTransform(458,330.2,0.894,0.894,0,0,0,32,73);

	this.mc5 = new window.lpcad0701s.mc6();
	this.mc5.setTransform(369.7,341.4,1.111,1.111,0,0,0,22.5,48);

	this.mc4 = new window.lpcad0701s.mc5();
	this.mc4.setTransform(237.1,365.8,1.026,1.026,0,0,0,44,13);

	this.mc3 = new window.lpcad0701s.mc4();
	this.mc3.setTransform(122.9,367.4,0.894,0.894,0,0,0,40.5,11);

	this.mc2 = new window.lpcad0701s.mc3();
	this.mc2.setTransform(306.6,300.3,0.894,0.894,0,0,0,22.1,18.1);

	this.mc1 = new window.lpcad0701s.mc2();
	this.mc1.setTransform(222.9,298.7,0.894,0.894,0,0,0,26.5,26);

	this.mc0 = new window.lpcad0701s.mc1();
	this.mc0.setTransform(121.1,296.9,0.894,0.894,0,0,0,42.6,27.6);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.mc0},{t:this.mc1},{t:this.mc2},{t:this.mc3},{t:this.mc4},{t:this.mc5},{t:this.mc6},{t:this.mc7},{t:this.pic5},{t:this.pic6},{t:this.pic7},{t:this.pic0},{t:this.pic2},{t:this.pic4},{t:this.pic1},{t:this.pic3}]}).to({state:[]},1).wait(1));

	// Layer 24
	this.obraz1 = new window.lpcad0701s.obraz2();
	this.obraz1.setTransform(521.9,132.1,0.894,0.894,0,0,0,113.5,136.1);

	this.obraz0 = new window.lpcad0701s.obraz1();
	this.obraz0.setTransform(197.2,132,0.894,0.894,0,0,0,113,137);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.obraz0},{t:this.obraz1}]}).to({state:[]},1).wait(1));

	// Layer 4
	this.instance = new window.lpcad0701s.Symbol10();
	this.instance.setTransform(369.2,202.5,1.028,0.9,0,0,0,359,225);

	this.timeline.addTween(Tween.get(this.instance).to({_off:true},1).wait(1));

}).prototype = p = new MovieClip();
p.nominalBounds = new Rectangle(0,0,720,405);


// symbols:
(window.lpcad0701s.btn_reset = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 5
	this.shape = new Shape();
	this.shape.graphics.f("#ffffff").p("AANhAIBDDFIDDhlIhkgjQADgQgCgZQgDgagIgZQgTg2hBgrQhXg5hnAeQh6AjggCAQgWBXAUBGQASBDBPA+IBLh1Qg3g7gRg7QgOg2AVgpQAWgsA8gWQBVgfBBBJQAYAbAMAgQAKAegIAMIhjgp").f();
	this.shape.setTransform(14,36.9);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.shape}]}).to({state:[]},1).wait(1));

	// Layer 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#c0850c").p("AhtjbQh6AjggCAQgWBXAUBGQASBDBPA+IBLh1Qg3g7gRg7QgOg2AVgpQAWgsA8gWQBVgfBBBJQAYAbAMAgQAKAegIAMIhjgpIBDDFIDDhlIhkgjQADgQgDgZQgCgagIgZQgTg2hBgrQhXg5hnAe").f();
	this.shape_1.setTransform(15,39.9);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#ffffff").p("ABwgXIhjgpIBDDFIDDhlIhkgjQADgQgDgZQgCgagIgZQgTg2hBgrQhXg5hnAeQh6AjggCAQgWBXAUBGQASBDBPA+IBLh1Qg3g7gRg7QgOg2AVgpQAWgsA8gWQBVgfBBBJQAYAbAMAgQAKAegIAM").f();
	this.shape_2.setTransform(15,39.9);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).wait(1));

	// Layer 4
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("#ffffff").p("AgJjcQgFAFAAAGIAAA8QAAAGAFAEQAEAFAFAAQAGAAAEgFQAFgEAAgGIAAg8QAAgGgFgFQgEgEgGAAQgFAAgEAE").p("AAAhoQgFAAgEAEQgFAFAAAGIAAA8QAAAGAFAEQAEAFAFAAQAGAAAEgFQAFgEAAgGIAAg8QAAgGgFgFQgEgEgGAA").p("AAKAUQgEgFgGAAQgFAAgEAFQgFAEAAAGIAAA8QAAAGAFAEQAEAFAFAAQAGAAAEgFQAFgEAAgGIAAg8QAAgGgFgE").p("AAKCMQgEgFgGAAQgFAAgEAFQgFAEAAAGIAAA8QAAAGAFAEQAEAFAFAAQAGAAAEgFQAFgEAAgGIAAg8QAAgGgFgE").f();
	this.shape_3.setTransform(54.5,40);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.shape_3}]}).wait(2));

	// Layer 1
	this.shape_4 = new Shape();
	this.shape_4.graphics.f("#ffb111").p("AH0jxIvnhsIBaK7IONAAIAApP").f();
	this.shape_4.setTransform(13,35);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.shape_4}]}).wait(2));

}).prototype = p = new MovieClip();
p.nominalBounds = new Rectangle(-36.9,0,100,70);


(window.lpcad0701s.btn = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("rgba(255,255,255,0.008)").p("AHbl2Iu1AAIAALtIO1AAIAArt").f();
	this.shape.setTransform(47.5,37.5);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0,0,95,75);


(window.lpcad0701s.pic4 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#cccccc").p("AJIgwQACgFAAgEQAAgkisgZQisgajyAAQjxAAisAaQisAZAAAkQAAAEADAFQACAFAHAFQAAAAACABQADACAFADQADACAEACIACAAQAAABABAAQAPADANAGQAqAMBGAKQAFAAAFABQAFABAEABQBCAJBNAFQAOABAPABQAGAAAGABQADAAAEAAQBcAFBrAAQACAAACAAIAJAAQADAAACAAQCWAAB6gKQAtgEApgFQAWgDAUgDQCRgVAXgcQABgCABgB").p("AASAQQh+AAhZgOQhZgNAAgTQAAgTBZgOQBZgNB+AAQB+AABaANQBZAOAAATQAAAThZANQhaAOh+AA").f("#a39d9d").p("ADqACQBZgNAAgTQAAgThZgOQhagNh+AAQh+AAhZANQhZAOAAATQAAATBZANQBZAOB+AAQB+AABagO").p("AF/A5Ql2BIl2hIQABADAAADQAAABAAAAQgBAJAHAIQAMANAPAKQALAIAMAFQFDA3E4g3QAMgFAKgIQAPgKANgNQAGgIgBgJQAAAAAAgBQAAgDABgD").f("#8a8888").p("AJGgtQgXAciRAVQgUADgWADQgpAFgtAEQh6AKiWAAQgCAAgDAAIgJAAQgCAAgCAAQhrAAhcgFQgEAAgDAAQgGgBgGAAQgPgBgOgBQhNgFhCgJQgEgBgFgBQgGgBgFAAQhGgKgpgMQAMAFAMAIQAYAPArALQAsAKANAMQAKAHACAHQF2BIF2hIQACgHAKgHQANgMAsgKQAsgLAYgPQAMgIAMgGQAMgGALgHQAKgGAFgH").f("#ababab").p("Ao/gkQAKAEAJAEQgEgCgDgCQgFgDgDgCQgCgBAAAAQgBAAgBAC").f();
	this.shape.setTransform(54.9,14.5);

	// Warstwa 3
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#cccccc").p("AJIgwQACgFAAgEQAAgkisgZQisgajyAAQjxAAisAaQisAZAAAkQAAAEADAFQACAFAHAFQgBAAgBACQAKAEAJAEIACAAQAAABABAAQAPADANAGQAqAMBGAKQAFAAAFABQgGgBgFAAQhGgKgpgMQAMAFAMAIQAYAPArALQAsAKANAMQAKAHACAHQABADAAADQAAABAAAAQgBAJAHAIQAMANAPAKQALAIAMAFQFDA3E4g3QAMgFAKgIQAPgKANgNQAGgIgBgJQAAAAAAgBQAAgDABgDQACgHAKgHQANgMAsgKQAsgLAYgPQAMgIAMgGQAMgGALgHQAKgGAFgHQABgCABgB").f();
	this.shape_1.setTransform(54.9,14.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-3.6,0,117.1,28.9);


(window.lpcad0701s.pic2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#af9797").p("AAykcQglgGgvgCQgbgBgfAAQg1AAgsAEQgZACgVADQgKACgJACQgoAJAAALQAAACABACQAHAJAgAGQAJACAKACQAVAEAZACQAsAEA1AAQAfAAAbgCQAvgCAlgGQAegFAPgGQAKgEAEgEQABgCAAgCQAAgHgPgGQgPgGgegF").p("AD6iJQAKAYAAAhQAAALgBAHQgIAig0ApQgFAEgGAEQg8AygHAaIAFAAQAFgSBFg4QAPgMAMgLIACADQAegUAHgUQAAgBABgFQAKgSAAgXQAAgNgLgUQgDgPgIgIQgCAAgBABQgBABgBAB").f("#cdb5b5").p("ACFikQgLAHgHAGIAAhqQgDABgDAAQgEAEgKAEIAAALIAAHxQAKgEAKgEIAAhmQAIAUAVAAQAIAAACgDQABgBAAgBQACABAAgNQAAgCgKgLQgKgMAAgCQAAgfAagXQALgLAtgZQAogXARgTQAageAAgsQAAhyhkAIQglADggAT").p("AD8iLQABgBACAAQAIAIADAPQALAUAAANQAAAXgKASQgBAFAAABQgHAUgeAUIgCgDQgMALgPAMQhFA4gFASIgFAAQAHgaA8gyQgkAXgOARQgRASgGAWIAAjYQABAAAAAAQAMAAAdgaQAegaAXAAQAUAAAWAc").p("AhcjjQg1AAgsgEIAAIDQBPAPBMgIIAAoIQgbACgfAA").p("AkskBIAAH9QAXAJAXAHIAAn9QgggGgHgJQgDAAgEgB").f("#c4a9a9").p("AgijlIAAIIQBBgHBAgYIAAnxIgtAAQglAGgvAC").f("#c6a0a0").p("ABfjtIAAgLQgPAGgeAFIAtAA").f("#dec9c9").p("Aj+jxIAAH9QAhAKAgAGIAAoDQgZgCgVgEQgKgCgJgC").f();
	this.shape.setTransform(30.1,25.8);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#af9797").p("AAykcQglgGgvgCQgbgBgfAAQg1AAgsAEQgZACgVADQgKACgJACQgoAJAAALQAAACABACQgDAAgEgBIAAH9QAXAJAXAHQAhAKAgAGQBPAPBMgIQBBgHBAgYQAKgEAKgEIAAhmQAIAUAVAAQAIAAACgDQABgBAAgBQACABAAgNQAAgCgKgLQgKgMAAgCQAAgfAagXQALgLAtgZQAogXARgTQAageAAgsQAAhyhkAIQglADggATQgLAHgHAGIAAhqQgDABgDAAQABgCAAgCQAAgHgPgGQgPgGgegF").p("AD6iJQAKAYAAAhQAAALgBAHQgIAig0ApQgFAEgGAEQgkAXgOARQgRASgGAWIAAjYQABAAAAAAQAMAAAdgaQAegaAXAAQAUAAAWAcQgBABgBAB").f();
	this.shape_1.setTransform(30.1,25.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0,-3.5,60.3,58.9);


(window.lpcad0701s.pic5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#d75600").p("AG3gRQAKgGAIgFQAJgFAEgIQgSAZh2ATQgQADgSADQghAFgkACQhCAHhMACQgiABglAAQgDAAgEAAQgBAAgCAAIgIAAQAAAAgBAAQgBAAgBAAQhXAAhKgEQgDgBgCAAQgFAAgFAAQgMgBgMgBQg+gFg1gIQgEgBgEgBQgEAAgEgBQg4gIgigLQAKAEAJAHQAUANAjALQAjAJALAKQAIAHACAGQEtBBEuhBQACgGAIgHQAKgKAkgJQAjgLATgNQAKgHAKgF").f("#ff9900").p("AHXgrQACgEAAgEQAAgTgugPQgigLg7gKQhqgSiOgEQAAAAgBAAQgggBgiAAQgKAAgJAAQgZAAgZAAQijADh4AUQgsAHgfAIQgJADgIADIAAAAQAAAAgBAAQguAQAAASQAAAEACAEQACAEAFAEQABACABAAQACACAEADQACAAABABIABAAQACABACABQAAABABAAQAMACALAGQAhALA5AIQAEABADAAQAEABAEABQA1AIA+AFQAMABAMABQAFAAAFAAQACAAADABQBKAEBXAAQABAAABAAQABAAAAAAIAIAAQACAAABAAQAEAAADAAQAlAAAigBQBMgCBCgHQAkgCAhgFQASgDAQgDQB2gTASgZQABgBAAgB").p("AFlgnQAAAEgDADQgLANgvALQgRADgWADQgNACgPACQg+AIhOADIhHABQgCAAgCAAQgIAAgHAAQgiAAgfgCQhXgDhEgLQhSgMgPgSQgDgDAAgEQAAgXBkgQQBLgMBhgDQAhgBAiAAQAjAAAgABQBhADBLAMQAqAHAYAHQAiAMAAAN").p("AmohDQAEgCAAgCQAEABAGADIAAAGQgHgBgGABIgBgG").p("AE1A6QAAAAAAgCQAAgCAAgDQkuBBkthBQAAADAAACQAAACAAAAQAAAIAFAHQAJAMANAJQAJAHAJAFQEGAxD7gxQAKgFAIgHQAMgJAKgMQAFgHAAgI").f("#b17751").p("AFDhAQgYgHgqgHQhLgMhhgDQgggBgjAAQgiAAghABQhhADhLAMQhkAQAAAXQAAAEADADQFZg6FHA6QADgDAAgEQAAgNgigM").f("#c28157").p("AEBgCQAWgDARgDQAvgLALgNQlHg6lZA6QAPASBSAMQBEALBXADQAfACAiAAQAHAAAIAAQACAAACAAIBHgBQBOgDA+gIQAPgCANgC").f("#ff9999").p("Amng9QAGgBAHABIAAgGQgGgDgEgBQAAACgEACIABAG").f("#ababab").p("AnPgjQAAACgBAAQAGADAGADQgBgBgCAAQgEgDgCgCQgBAAgBgC").f();
	this.shape.setTransform(44.1,14.8);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#d75600").p("AG3gRQAKgGAIgFQAJgFAEgIQABgBAAgBQACgEAAgEQAAgTgugPQgigLg7gKQhqgSiOgEQAAAAgBAAQgggBgiAAQgKAAgJAAQgZAAgZAAQijADh4AUQgsAHgfAIQgJADgIADQABAAgBAAQAAAAgBAAQguAQAAASQAAAEACAEQACAEAFAEQAAACgBAAQAGADAGADIABAAQACABACABQAAABABAAQAMACALAGQAhALA5AIQAEABADAAQgEAAgEgBQg4gIgigLQAKAEAJAHQAUANAjALQAjAJALAKQAIAHACAGQAAADAAACQAAACAAAAQAAAIAFAHQAJAMANAJQAJAHAJAFQEGAxD7gxQAKgFAIgHQAMgJAKgMQAFgHAAgIQAAAAAAgCQAAgCAAgDQACgGAIgHQAKgKAkgJQAjgLATgNQAKgHAKgF").f();
	this.shape_1.setTransform(44.1,14.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-3.1,1.8,94.6,26);


(window.lpcad0701s.pic3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#006600").p("Ag/jJQgLAAgIADQgCABAAABQgCABgBABIAAABQgCACAAADQAAABAAABQABAEAFADQAAAAABABQAAAAABAAQAIAEAKAAQAFAAAEgBQADAAANgMQABAAAAgBQAAABgBAAQgHAJAAAAQAEgCABgCQADgBAAgCIAAgBQAAgBAAgBQAAgBAAgBIAAAAQAAgBgBgCIAAAAQgCgCgFgDQgHgDgLAA").f("#00cc00").p("AgmjBQAAAAABgBQgBABAAAAIAAAA").p("Agli/QAAAAAAABIAAAAQAAAAAAgB").p("Agmi7QgNAMgDAAQgEABgFAAQgKAAgIgEIAQA2IAPA2IAHAKIAQgCIAEgDIgCgFQgOgcgDgdQgEgbAGgcQgBACgEACQAAAAAHgJIAAAA").p("AhXjpQABgBACgCQgCgBgBgCIAAAG").f("#ff3232").p("ADZBmQAJgXAAgaQAAgMgBgLQgDgegOgaQgKgRgLgNQgTgYgagSQgigWgpABQgUAEgLADIABAAQgfALgFAkQAUACAUAIQARAHAIAQQAFAJADAJIgEgCIgXgZIgIgDIAFACQhGgbgmA/QgdAvAGAJIgCAAQABg1ApglIgQgMQg0gOgxAgIAOgMQArgiAsAWIADgPIAKADIgPg2QgDABgDABQgoAMgNAOQgNAPgEAKQgDAMgJAJQgIAJgKAEQgJAEgOAKQgNAKgJAeQgJAeAAAkQAAAgAQAcQAMAVAQAQQAtATAtgLQAVgFAWgEQAtAsA6gUQAwgSAhgoIAkAPQARgMANgRQADgEAPgnIgMAgQAFgIAEgK").p("ABigfQgLgDgIgEQgIgEgGgFQgOgKADgJQACgKARgCQAPgCAUAFQABAAABAAQAUAGANAKQANALgDAJQgCAJgQACQgRACgUgF").p("ABEBHQAAAXgRAQQgRAQgYAAQgXAAgRgQQgRgQAAgXQAAgXARgQQARgQAXAAQAYAAARAQQARAQAAAX").p("Ah2gOQAKAGAAAOQAAACAAADQgBAOgIAOQgKAQgOAIQgIAEgHAAQgEAAgEgCQgKgGAAgQQgBgPAJgRQAKgPAOgIQAOgIAKAG").p("AAkhwQgJgDgGgCQgigLgdABQADAdAOAcIAGgEIAHACQAKgoAmAA").f("#fe7373").p("ACHgcQAQgCACgJQADgJgNgLQgNgKgUgGQgBAAgBAAQgUgFgPACQgRACgCAKQgDAJAOAKQAGAFAIAEQAIAEALADQAUAFARgC").p("AAzAgQgRgQgYAAQgXAAgRAQQgRAQAAAXQAAAXARAQQARAQAXAAQAYAAARgQQARgQAAgXQAAgXgRgQ").p("AiOgMQgOAIgKAPQgJARABAPQAAAQAKAGQAEACAEAAQAHAAAIgEQAOgIAKgQQAIgOABgOQAAgDAAgCQAAgOgKgGQgKgGgOAI").f("#e51b1b").p("ADQB4IAMggQgPAngDAEQgNARgRAMIgkgPQghAogwASQg6AUgtgsQgWAEgVAFQgtALgtgTQAUAWAYAMQAlAUAlgWQAMAKAOAHQAMAIAPABQAiAGAjgIQA2gOAjgmIARAAQAEgBAEgDQAagPASg/QgEAKgFAI").f("#990000").p("AAkhwQgmAAgKAoIgHgCIgGAEIACAFIgEADIgQACIgHgKIgKgDIgDAPQgsgWgrAiIgOAMQAxggA0AOIAQAMQgpAlgBA1IACAAQgGgJAdgvQAmg/BGAbIgFgCIAIADIAXAZIAEACQgDgJgFgJQgIgQgRgHQgUgIgUgCQAFgkAfgLIgBAA").f();
	this.shape.setTransform(22,12.4);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#ff3232").p("Ag/jJQgLAAgIADQgCABAAABQgCABgBABIAAABQgCACAAADQAAABAAABQABAEAFADQAAAAABABQAAAAABAAIAQA2QgDABgDABQgoAMgNAOQgNAPgEAKQgDAMgJAJQgIAJgKAEQgJAEgOAKQgNAKgJAeQgJAeAAAkQAAAgAQAcQAMAVAQAQQAUAWAYAMQAlAUAlgWQAMAKAOAHQAMAIAPABQAiAGAjgIQA2gOAjgmIARAAQAEgBAEgDQAagPASg/QAJgXAAgaQAAgMgBgLQgDgegOgaQgKgRgLgNQgTgYgagSQgigWgpABQgUAEgLADQgJgDgGgCQgigLgdABQgEgbAGgcQADgBAAgCIAAgBQAAgBAAgBQAAgBAAgBQAAAAAAgBQAAAAAAABQAAgBgBgCQAAAAABgBQgBABAAAAQgCgCgFgDQgHgDgLAA").p("Agmi7QABAAAAgBQAAABgBAAIAAAA").p("AhXjpQABgBACgCQgCgBgBgCIAAAG").f();
	this.shape_1.setTransform(22,12.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-0.6,-11.6,45.2,48.1);


(window.lpcad0701s.pic1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#a17d02").p("AmvjwIgKgJIBTBIIARgbIhPhUIgLAw").p("AG0A6QgJgJgKAFQgBAAAAABQAAAAgBAAIAAADQAAABADAPQAAADABACQADAHAFADQACABADAAQAFAAADgHQADgFAAgGQAAgHgHgH").f("#ffcc00").p("AlmixQAQAWAVAcQACACACADIAEgFQBWB9CKA9QB4A3CFARQCKAUB1hIQgBgCAAgDQgDgPAAgBIAAgDQiMAriRgfQiLgdh7hNQhwhIhhhdIgRAb").f("#e4af01").p("AGrBZQgFgDgDgHQh1BIiKgUQiFgRh4g3QiKg9hWh9IgEAFIgIgCQAVBDAYAwQA+B6B2BEQCEBNCZgdQCRgZBhhyIAAgB").f("#d3a301").p("AC5DlQiZAdiEhNQh2hEg+h6QgYgwgVhDQgDBfApBVQBCCLCNA9QCLA8CSgvQCSgvBMiEQhhByiRAZ").f();
	this.shape.setTransform(33.4,21.9);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#a17d02").p("AmvjwIgKgJIBTBIQAQAWAVAcQACACACADIgIgCQgDBfApBVQBCCLCNA9QCLA8CSgvQCSgvBMiEIAAgBQACABADAAQAFAAADgHQADgFAAgGQAAgHgHgHQgJgJgKAFQgBAAAAABQAAAAgBAAQiMAriRgfQiLgdh7hNQhwhIhhhdIhPhUIgLAw").f();
	this.shape_1.setTransform(33.4,21.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-10.7,-6.9,88.5,57.9);


(window.lpcad0701s.pic8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#cccccc").p("AgKgRQAAA/AHATQADgCABgDQAAgBAAAAQABAAABABQAEgBACgDQAAgZACgqQABgIAAgGQAAgCAAgBQAAgHgBgHQAAgBAAgCQgBgLgDgIQgGADgCAGQgBgBgBgCQgHAEAAAl").f();
	this.shape.setTransform(17.7,8.1);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#cccccc").p("AAzq+QgBBigGByQgBAHAAAJQgBAHAAAIQgMBkgxDDQgIAegZGZQgYGYAlABIAPgFQA/Bwgnl4Qgnl5Alh/QAkiBAIhMQAFhMAFhYIAAAAIABgPQABgIABgHQAAgBAAgBQAHhlAAhwIgLAB").f();
	this.shape_1.setTransform(12.2,85.5);

	// Warstwa 3
	this.shape_2 = new Shape();
	this.shape_2.graphics.f("rgba(71,35,35,0.867)").p("AghqgQgEgKgKgEQgEAIgDAMQgBgCAAgCIACgLQgRAGgDAZQgCAMACAQQAAE3A9CVQAeBQAJAtQAQBHADB1QgCA5gGAfIAACkQAAAWgDAXQgLB6AABVQAAALAFAIQADAFAIAJQANgCAFgGQAAgBAAgCQAFgCADgCIACgLIAAkVQAHiyAAgJQAAgbAAgXQAAgVAAgYQAAiAgdhgQhCjfgNgyIAAkW").f();
	this.shape_2.setTransform(32,84.4);

	// Warstwa 4
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("rgba(71,35,35,0.867)").p("AgJptQgmgFgSgXIgGABIAAAUIgMAAQAEEZhECAQhFCAAMA8IgELkQAIgUA0gOQA+gRBWAAQBVAAA9AQQAEApAHAoQAggKANgLQAJgIAAgKQAAgKgJgHIAAq7IgFgnQgOhAhIiHQhHiIA4kMIgQAAIAAgFIgHgCQguAigkgG").p("Ag6gvQgIgBgDgBQgCgDAAgMQAAgKASg8QATg+ACgrIAOgBQAJAaAAAmQAAAbgPAuQgRA0gRAE").p("AhZAuQgFgEAAgGQAAgpAnACIAEgBQAEAAAAALQAAAJgIAUQgKAVgIAEQgNgLgDgE").f("#cccccc").p("AgYhnQAPguAAgbQAAgmgJgaIgOABQgCArgTA+QgSA8AAAKQAAAMACADQADABAIABQARgEARg0").p("AhJA9QAIgEAKgVQAIgUAAgJQAAgLgEAAIgEABQgngCAAApQAAAGAFAEQADAEANAL").f("#333333").p("ABJqJQAEgBADAAIAAhyQgDgCgEgBQgcgGgpAAQgoAAgdAGQgEABgCABIAABzQACAAAEABQASAXAmAFQAkAGAugi").f("rgba(49,22,22,0.867)").p("AAAKSQhWAAg+ARQg0AOgIAUQgBADAAAEQAAAEABAEQAIATA0AOQA+ARBWAAQBYAAA9gRQAFgBADgBQgHgogEgpQg9gQhVAA").f();
	this.shape_3.setTransform(22.2,78.2);

	// Warstwa 5
	this.shape_4 = new Shape();
	this.shape_4.graphics.f("rgba(71,35,35,0.867)").p("ABQqDIAAgFIgHgCQAEgBADgBIAAhxQgDgCgEgBQgcgHgpAAQgoAAgdAHQgEABgCAAIAABzQACABAEABIgGAAIAAAVIgMAAQAEEZhECAQhFCAAMA8IgELkQgBADAAAEQAAADABAEQAIAUA0AOQAQAEARAEQAQAWAIgTQAqAGAxAAQBYAAA9gRQAFgBADgCQAggJANgMQAJgIAAgJQAAgKgJgIIAAq7IgFgmQgOhAhIiHQhHiIA4kMIgQAA").f();
	this.shape_4.setTransform(22.2,78.4);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(1.1,0.8,42.2,155.1);


(window.lpcad0701s.pic7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#cc65cc").p("AiYrTQgCABgCgBQgBAAgBABQgCAAgDAAIACADQgBACgBADQgBABAAAAQgBgCgBgDIgDABIgHAjQgBAAgFgEQATAZAAATQAAAFgBAEIgEAAQgJglgJgRIABgBQgDgBgDgDQgNgKgSAAQgFAAgEAEQACAQAAAaQADAcAPATQgCACgBABQgIgHgHgiQgGgbgBgNQAAAEgBAFQgBAMABANQgsgDgKADQgGACAAALQAAANANAOQAGAGANAKQALAFArATIACAEQADACgGAAQgMAAgRgHQgOgGgIgJQgmAFgPAHQgOAGAAAMQAAAJATAHQAJAEATAGQAFgEAKgGQAWgMAFABQgWAPgPAIQABAAAAAAIgDACQgUAPgLATQgLATAAARQgDARANAAQACAAAEgCQAAAAAAgEQAAAAAVgPQAIgGALgIQATgMAQgMQAagTATgOIAEADQggAigTAQQgLAIgJAHQgCANACASQAEAiAAAFIABABQABABAEAAQAFAAALgNQALgOAAAAQAAAnAcAAQAUAAARgbQAJgQAEgIQgGgEgFgNQgHgPAAgFQADgNAAgHIACAAQAGAXACAGQAFAPAGAJQAEAEAKAHQAPAMAGAAQAHAAABgMQABgOAAgEQAAABANAKQAFAFAIAHQABABABABQAZAUALAAQAJAAABgIQAAgLAAgEQAAgSgFghQAgADALgDQAHgCAAgHQAAgDgKgTQgJgSgDgEIAEgBQAVgCAGgCQALgDAAgHQAAgIgRgPQgUgQgGgFQAHgEAMgHQAIgGAAgJQAAgHgKgCIgpAAIgUACIAAgBQAeg9AAgKQgBgEAAgDQAAgBgHAAQgaAAgWAMQgIAEgOALQABgXAAgLQABgVgTgBQgPALgKAUQgIgJgEgFQgGgHgHgDQAAgDgBAA").p("AgOqkQAAAKgTAdQgRAcgIAFIgCAAQAEgKAohAIABgBQABAAAAAD").p("AharLIACAAQACAMAAARQAAAJgNA0IgEABQgBgDAAgDQAAgFAGgjQAHgkABgJ").p("Ag9pGQgCgBAAgBQABgBA2ABQADACAFADQgCABgEAAIg+gBQAIgCgBgB").p("Ag4omQAPgEAQAHQAIAFAPAIQAAAAAAACQAAAAgDAAQgIAAgQgHQgUgKgHgB").p("AhsooQgNALgTAAQgSAAgOgLQgNgLAAgPQAAgPANgLQAOgKASAAQATAAANAKQANALAAAPQAAAPgNAL").p("AhWndQAAAKAAAFQAAAFAAACIAAABQgBAJgHANQgBAAAAgBQgBAAAAgFQABgQACgPQAAgBAAgBQACgbABgRIACAAQACASAAAU").p("AganfQgQAAgKgVQgJgWgEgDQAKACAIARQAJARASAHQgBABAAABQgBABgEAA").p("Aixn7QABAAAAADQAAALgUAgQgUAhgIABIgCgBQAgg6AQgVIABAA").f("#ad4dad").p("AgPqnIgBABQgoBAgEAKIACAAQAIgFARgcQATgdAAgKQAAgDgBAA").p("AhiqeQgGAjAAAFQAAADABADIAEgBQANg0AAgJQAAgRgCgMIgCAAQgBAJgHAk").p("AhEpDIA+ABQAEAAACgBQgFgDgDgCQg2gBgBABQAAABACABQABABgIAC").p("AgdobQAQAHAIAAQADAAAAAAQAAgCAAAAQgPgIgIgFQgQgHgPAEQAHABAUAK").p("AhYoDIgCAAQgBARgCAbQAAABAAABQgCAPgBAQQAAAFABAAQAAABABAAQAHgNABgJIAAgBQAAgCAAgFQAAgFAAgKQAAgUgCgS").p("AgVngQAAgBABgBQgSgHgJgRQgIgRgKgCQAEADAJAWQAKAVAQAAQAEAAABgB").p("Aiyn7QgQAVggA6IACABQAIgBAUghQAUggAAgLQAAgDgBAAIgBAA").p("Ai6qvQAJARAJAlIAEAAQABgEAAgFQAAgTgTgZQgBgBgBgBIgBAAIgBAB").p("AjTphQgPgTgDgcQAAgagCgQQAAgCAAgDIgCAAQgDAOAAABIAAABQABANAGAbQAHAiAIAHQABgBACgC").p("AkMpWQACAFADAEQAIAJAOAGQARAHAMAAQAGAAgDgCIgCgEQgrgTgLgFQgDgBAAAA").p("AkMofQgKAGgFAEQgHAGgBADQAGgCAHgFQAPgIAWgPQgFgBgWAM").p("AkKndQgLAIgIAGQgVAPAAAAQAAAEAAAAIAAABQABAAACAAQAYgGAagRQAJgHALgIQATgQAggiIgEgDQgTAOgaATQgQAMgTAM").p("AiZnqQAAAHgDANQAAAFAHAPQAFANAGAEQADADADAAQAHAAgDgCQgCgCgCgDQgGgJgFgPQgCgGgGgXIgCAA").f("#fee17c").p("AhfpCQAAgPgNgLQgNgKgTAAQgSAAgOAKQgNALAAAPQAAAPANALQAOALASAAQATAAANgLQANgLAAgP").f("#247b23").p("AE9kxIgBAIIACgIQAAgBAAgBQgBABAAAB").p("ACRBjIB3lgQg7BnglBvQgUA5gNA8QgCAJgCAJIAOAEIAAgB").p("AhUltQAxBrAqBpQAvBzAnB0QADALAEAJQAAACAAAAIAAAAIADAFIABgFIABAAIAAAAQAAgBABgBIgFAAQgDgKgDgKQhBjkgyiPQgdgmgjgi").p("ABuBGQABAEABAEQABAEABAEQACgDABgFQAEgSABghIgMAr").p("AChBrQAFgEAFgDQANgLAMgLQAngkAZguQBGiFgOiYQgCCWhGB/QgdAzgsAnQgLALgNAKQgBABAAAAIAPAAIAAAH").p("ABqA5QADhmgphgQgYg4gggyQAIAYAHAVQARA3A+DM").f("#33b033").p("AE+kxIgCAIIABgIQhsAugdBnQgeBngcBQQgBAhgEASQgBAFgCADQACAHACAGIgMgBQgBABAAABIABAAIA3AAIgPAAQAAAAABgBQANgKALgLQAsgnAdgzQBGh/ACiWQgBgCAAgDQABgBAAAAQACgDACgDIAAgFQgBABgBAA").p("ACRBkIgOgEQACgJACgJQANg8AUg5QAlhvA7hnIh3FgIAAAB").p("Ahbl0QAKBiAZBeQAmCQA8ByQAFALAGAKIAGAAIApABIAAAAQAAAAAAgCQgEgJgDgLQgnh0gvhzQgqhpgxhrQgEgDgDgE").p("ABqBkIgBAAIgBAAIACAA").f("rgba(13,42,13,0.878)").p("Ag+mlQgIgHgFgFQAZA3AeBVQAyCPBBDkQADAKADAKIAFAAIAMABQgCgGgCgHQgBgEgBgEQgBgEgBgEQgCgHgCgGQg+jMgRg3QgHgVgIgYQgOgqgUgzQgRgqgVglQgBgBgBgB").f("#0066ff").p("AAnBkQABAPAPAhQASAqADAIQAAABABABQAHAUABAeQAAAIAAAqQAAAvgEAfQgEAWgLBJQgBAIgEAJQAIAEAIADQABgGABgFQAYhxAehvQAZCEgvBtQAUABAVgGQAwgOACgWQgDgOgBgPIAAhKQAAhJAIgmQAFgbAEgXQAPhSACgNQgHgDg2AAQgFADgFAEIAAgHIg3AAIgCAAIgBAFIgDgFIgpgBQgMAAgIAB").p("ABpBkIABAAIgBAAIAAAA").f("#0460e9").p("ACYHyQgVAGgUgBQgYA2gqAxQgMAPgXAGIgJgGQA4gtAUhPQgIgDgIgEQgMAbglAmQgEAEgDAEQg1A2AAAdQAAATAUATQApgXAvAFQAsgCAqgKQAVgEAygRQAygRAAgVQgBgVADgHQgKgJgIgJQgYgXgLgVQgKgSgEgZQgCAWgwAO").f("#055ad9").p("AELJTQAAAVgyARQgyARgVAEQgqAKgsACQgvgFgpAXQAhAhAuAGQAxAIAwgEQAYgBAYgCQAegDAdgGQAMgBALgGQAVgMAQgPQANgOADgVQACgNgJgLQgYgfgfgYQgDAHABAV").f("#4c8dee").p("ABNHxQgUBPg4AtIAJAGQAXgGAMgPQAqgxAYg2QAvhtgZiEQgeBvgYBxQgBAFgBAG").f();
	this.shape.setTransform(32.3,72);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#472323").p("AijrSIACADQgBACgBADQgBABAAAAQgBgCgBgDIgDABIgHAjQgBAAgFgEQgBgBgBgBIgBAAQgDgBgDgDQgNgKgSAAQgFAAgEAEQAAgCAAgDIgCAAQgDAOAAABIAAABQAAAEgBAFQgBAMABANQgsgDgKADQgGACAAALQAAANANAOQAGAGANAKQgDgBAAAAQACAFADAEQgmAFgPAHQgOAGAAAMQAAAJATAHQAJAEATAGQgHAGgBADQAGgCAHgFQABAAAAAAIgDACQgUAPgLATQgLATAAARQgDARANAAQACAAAEgCIAAABQABAAACAAQAYgGAagRQgCANACASQAEAiAAAFIABABQABABAEAAQAFAAALgNQALgOAAAAQAAAnAcAAQAUAAARgbQAJgQAEgIQADADADAAQAHAAgDgCQgCgCgCgDQAEAEAKAHQAPAMAGAAQAHAAABgMQABgOAAgEQAAABANAKQAZA3AeBVQgdgmgjgiQgEgDgDgEQAKBiAZBeQAmCQA8ByQAFALAGAKIAHAAQgMAAgJABQABAPAPAhQASAqADAIQAAABABABQAHAUABAeQAAAIAAAqQAAAvgEAfQgEAWgLBJQgBAIgEAJQgMAbglAmQgEAEgDAEQg1A2AAAdQAAATAUATQAhAhAuAGQAxAIAwgEQAYgBAYgCQAegDAdgGQAMgBALgGQAVgMAQgPQANgOADgVQACgNgJgLQgYgfgfgYQgKgJgIgJQgYgXgLgVQgKgSgEgZQgDgOgBgPIAAhKQAAhJAIgmQAFgbAEgXQAPhSACgNQgHgDg2AAQANgLAMgLQAngkAZguQBGiFgOiYQgBgCAAgDQABgBAAAAQACgDACgDIAAgFQgBABgBAAQAAgBAAgBQgBABAAABQhsAugdBnQgeBngcBQIgMArQgCgHgCgGQADhmgphgQgYg4gggyQgOgqgUgzQgRgqgVglQAZAUALAAQAJAAABgIQAAgLAAgEQAAgSgFghQAgADALgDQAHgCAAgHQAAgDgKgTQgJgSgDgEIAEgBQAVgCAGgCQALgDAAgHQAAgIgRgPQgUgQgGgFQAHgEAMgHQAIgGAAgJQAAgHgKgCIgpAAIgUACIAAgBQAeg9AAgKQgBgEAAgDQAAgBgHAAQgaAAgWAMQgIAEgOALQABgXAAgLQABgVgTgBQgPALgKAUQgIgJgEgFQgGgHgHgDQAAgDgBAAQgCABgCgBQgBAAgBABQgCAAgDAA").f();
	this.shape_1.setTransform(32.3,72);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-0.7,-0.7,66.2,145.6);


(window.lpcad0701s.pic6 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#a9a954").p("AhCihQA0BPAjBoQAgBYASBVQADgLABgJQAqjViqiIIgDgVQgGARgEAR").f("#989842").p("AhCihQhDDoDKB+IACgCIAAAAQgShVgghYQgjhog0hP").f();
	this.shape.setTransform(68,46.8);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#a9a954").p("AgSiqQAeBYAIBrQAGBbgDBUQAFgJADgJQBei9h+itIACgUQgKAPgJAP").f("#989842").p("AgSiqQh4DKCeCqIADgCQADhUgGhbQgIhrgehY").f();
	this.shape_1.setTransform(46.2,46.3);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#989842").p("ACVoLQADACACAAQAKAfAmB0QANApAKAgQAMAkAHAcQAEgIABgEQADgIAAgKQAAgEAAgFQgFgrgrh5QgYhFgahHQgaAOgiCeQgeCOAAA0QAAABAAABQACAJAWgJQApjJAQh0QACACACAE").p("AAjmSQgfBYgNAwQgLhWgukZQgEACgCADIgBAAQgfA7gsCFQgRA0gLAfQgEAOgDAJQAPAAAEAMQAHgNAGgRQAVgwAXhKQAUhAAKgkQAGA/AuEnQABADAAADIAQgFIAeARQgBgJgBgJQgHhoAfhFIAHAzIAKABIAAg6IgOgKIgMgB").f("#957764").p("ABAjUIgsAAQABAJABAJIgegRIgQAFQAAgDgBgDIgGAAQgJBigMByQgLB1g8CDQg2B0ABCBQAAARADAQQAIACAGACQElBaBZjsQgOhHgehBQg8iDgLh1QgMhygIhiQgWAJgCgJ").f("#e3a401").p("AjamvIgOAIQgNAXAHAaQADAMAHALQAIANAKAMQgtAHglAdQgQANgLARQgMATgJATQAUAEASgDQAGgDAGgCQg6A1gSBLQBAgZApg6QgdBTAHBZQBIhKAPhjQgEAhALAfQAKAaAaANQAbg3gBg9QAAgygdgoQAmgDAUgdQAFgHAQgaQgSgQgXAAQgPADgMAKQgCADgEACQgGARgHANQACAFAAAHQAAAYgZAAQgKAAgBgBIgIgDQAAAAgDgEQgDgDAAgKQAAgWAZgEQADAAABgBQADgJAEgOQgIgcgLgcQgHgPgQgH").f("#efd097").p("AjRkiQADAEAAAAIAIADQABABAKAAQAZAAAAgYQAAgHgCgFQgEgMgPAAQgBABgDAAQgZAEAAAWQAAAKADAD").f("#6d5444").p("ADPJBQAZgkAAgwQAAg4gJg1QhZDsklhaQgGgCgIgCQAGAcARAXQAeArAyAPIDFAAQAygPAegr").f();
	this.shape_2.setTransform(39.6,63.8);

	// Warstwa 3
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("#989842").p("ACVoLQADACACAAQAKAfAmB0QAIAYAGAUQhCDpDKB8IACgCIAAAAQADgLACgJQAojPigiHQgNgpgWg+QgYhFgahHQgaAOgiCeQgIAqgHAiQgHgLgIgMIACgUQgDAEgCADIAAgXIgOgKIgMgBQgfBYgNAwQgLhWgukZQgEACgCADIgBAAQgfA7gsCFQgRA0gLAfQgIgcgLgcQgHgPgQgHIgOAIQgNAXAHAaQADAMAHALQAIANAKAMQgtAHglAdQgQANgLARQgMATgJATQAUAEASgDQAGgDAGgCQg6A1gSBLQBAgZApg6QgdBTAHBZQBIhKAPhjQgEAhALAfQAKAaAaANQAbg3gBg9QAAgygdgoQAmgDAUgdQAFgHAQgaQgSgQgXAAQgPADgMAKQgCADgEACQAVgwAXhKQAUhAAKgkQAGA/AuEnIgGAAQgJBigMByQgLB1g8CDQg2B0ABCBQAAARADAQQAGAcARAXQAeArAyAPIDFAAQAygPAegrQAZgkAAgwQAAg4gJg1QgOhHgehBQg8iDgLh1QgBgGgBgIQA+iOhBiGQAdiSANhdQACACACAE").p("AAvlZQgPAagLAYQAGgyARgoIAFAkQgBACgBAC").f();
	this.shape_3.setTransform(39.6,63.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(3,0.4,73.4,126.9);


(window.lpcad0701s.mc8 = function() {
	this.initialize();

	// Warstwa 7
	this.shape = new Shape();
	this.shape.graphics.f("#cccccc").p("AAHgfQAAgHgDgFQgDABgCAEQAAgBgBgBQgFADAAAZQAAArAFAOQACgCAAgCQABgBgBAAQABABABAAQACAAABgCQAAgSACgcQABgGAAgEQAAgBAAgBQAAgFAAgEQgBgBAAgC").f();
	this.shape.setTransform(12.6,5.8);

	// Warstwa 5
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#cccccc").p("AAjniQgBBDgEBOQAAAFgBAFQAAAGgBAFQgHBGghCFQgGAWgREYQgREZAaABIAKgEQAqBOgakDQgbkEAahXQAZhYAEg1QAFg0ADg9IAAgBIAAgKQABgEAAgGQAAAAAAgBQAGhFAAhNIgIAB").f();
	this.shape_1.setTransform(8.7,59.1);

	// Warstwa 6
	this.shape_2 = new Shape();
	this.shape_2.graphics.f("rgba(71,35,35,0.867)").p("AglnUQgLAEgCARQgBAJABAKQAADWApBnQAVA2AGAgQALAwACBRQgBAngEAWIAABwQgBAQgBAPQgIBUAAA7QAAAIAEAFQACADAGAGQAIgBAEgEQAAgBAAgBQADgBACgCIABgHIAAi/QAFh6AAgHQAAgSAAgRQAAgOAAgQQAAhYgUhCQgtiagJgiIAAi/QgCgHgIgDQgCAGgDAIQABgCgBgBIABgH").f();
	this.shape_2.setTransform(22.4,58.3);

	// Warstwa 4
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("rgba(71,35,35,0.867)").p("AA3m6IAAgEIgFAAQggAXgZgEQgZgDgMgQIgFAAIAAAOIgJAAQADDBgvBYQguBZAHAqIgCH8QAGgNAjgKQArgMA7AAQA6AAAqALQADAcAFAcQAWgHAJgIQAGgGAAgGQAAgGgGgGIAAnhIgEgaQgKgsgwhdQgxheAli5IgKAA").p("AgRhGQgLAkgMACQgGAAgBgBQgCgCAAgIQAAgHAMgqQAOgqABgeIAKAAQAFARAAAbQAAASgKAg").p("AgyAqQgJgHgDgDQgCgDAAgEQAAgcAaABIADAAQACAAAAAHQAAAHgFANQgGAPgGAC").f("#cccccc").p("AgHh4QAAgbgFgRIgKAAQgBAegOAqQgMAqAAAHQAAAIACACQABABAGAAQAMgCALgkQAKggAAgS").p("AgmAZQAFgNAAgHQAAgHgCAAIgDAAQgagBAAAcQAAAEACADQADADAJAHQAGgCAGgP").f("#333333").p("AAyoPQgUgFgbAAQgbAAgUAFQgDABgCAAIAABPQACAAADABQAMAQAZADQAZAEAggXQADgBACAAIAAhPQgCAAgDgB").f("rgba(49,22,22,0.867)").p("ABkHQQgqgLg6AAQg7AAgrAMQgjAKgGANQgBACAAADQAAADABACQAGANAjAKQArAMA7AAQA8AAArgMQACgBADAAQgFgcgDgc").f();
	this.shape_3.setTransform(15.6,54.1);

	// Warstwa 8
	this.shape_4 = new Shape();
	this.shape_4.graphics.f("rgba(71,35,35,0.867)").p("AA3m6IAAgFIgFAAQADgBACgBIAAhOQgCAAgDgBQgUgFgbAAQgbAAgUAFQgDABgCAAIAABOQACABADABIgFAAIAAAPIgJAAQADDAgvBYQguBZAHApIgCH9QgBACAAADQAAADABACQAGANAjAKQALADALACQAMAQAFgNQAdAEAiAAQA8AAArgMQACgBADAAQAWgHAJgIQAGgGAAgGQAAgGgGgHIAAnfIgEgbQgKgsgwhdQgxheAli4IgKAA").f();
	this.shape_4.setTransform(15.6,54.2);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(1.1,0.8,29,106.8);


(window.lpcad0701s.mc7 = function() {
	this.initialize();

	// Warstwa 4
	this.shape = new Shape();
	this.shape.graphics.f("#cc65cc").p("AgMioQgDABgCgBQAAAAgBABQgCAAgDAAIACADQgBACgCADQAAABgBAAQAAgCgCgDIgCABIgHAjQgBAAgFgEQASAZAAATQAAAFgBAEIgDAAQgKglgIgRIABgBQgDgBgEgDQgMgKgSAAQgFAAgEAEQACAQAAAaQACAcAPATQgBACgCABQgIgHgHgiQgFgbgBgNQAAAEgBAFQgBAMABANQgtgDgKADQgFACAAALQAAANANAOQAGAGANAKQALAFAqATIACAEQAEACgGAAQgMAAgRgHQgOgGgIgIQgmAEgPAHQgOAGAAAMQAAAIATAHQAJAEASAGQAGgEAKgGQAWgLAFAAQgWAPgPAIQABAAAAABIgDABQgUAPgLATQgLATAAASQgDARANAAQACAAAEgCQAAgBAAgEQAAAAAogcQAygjAdgXIAFAEQggAigUAPQgKAIgKAHQgBANABATQAEAhAAAGIABABQACAAADAAQAGAAAKgMQAMgOAAAAQAAAnAcAAQATAAASgcQAJgQADgIQgFgEgFgMQgHgQAAgEQADgOAAgHIACAAQAGAXACAGQAEAPAGAJQAEAEAKAIQAPALAFAAQAHAAACgMQABgOAAgEQAAABAZAWQAbAWAMAAQAIAAACgIQAAgKAAgEQAAgTgFghQAhADAKgDQAIgBAAgHQAAgDgKgTQgJgSgEgEIAEgBQAWgDAGgBQALgDAAgIQAAgHgSgOQgUgRgGgFQAIgEAMgHQAIgGAAgJQAAgHgKgCIgqAAIgUACIAAgBQAeg9AAgKQgBgEAAgDQAAgBgHAAQgaAAgWAMQgIAEgPALQACgXAAgLQAAgVgSgBQgPALgKAUQgIgJgEgFQgFgHgHgDQAAgDgBAA").p("AB8h8QABAAAAADQAAAKgTAdQgSAdgHAEIgDAAQAFgJAohBIABgB").p("AAzigQACAMAAARQAAAJgNA0IgEABQgCgDAAgDQAAgFAHgjQAHgkAAgJIADAA").p("ABMgcQAAgCA3ABQACACAFADQgBACgEAAIg+gCQAHgCAAgBQgCgBAAAA").p("ABxAIQAJAEAPAIQAAABAAABQAAABgDAAQgIAAgQgIQgUgJgHgCQAPgEAPAI").p("AAfACQgNALgSAAQgSAAgOgLQgNgJAAgPQAAgQANgKQAOgLASAAQASAAANALQANAKAAAQQAAAPgNAJ").p("AAzAnQACASAAAVQAAAVAAABQgCAKgGANQgBgBgBgBQAAAAAAgFQAFgzAAgaIADAA").p("AB2BKQgCABgDAAQgQAAgLgVQgIgVgFgEQAKACAIARQAKASARAHQAAABAAAA").p("AglAvQAAAAAAAEQAAAKgTAhQgUAggJACIgBgCQAfg5ARgVIABgB").f("#ad4dad").p("AB7h7QgoBBgFAJIADAAQAHgEASgdQATgdAAgKQAAgDgBAAIgBAB").p("AAwigQAAAJgHAkQgHAjAAAFQAAADACADIAEgBQANg0AAgJQAAgRgCgMIgDAA").p("ABOgbQAAABgHACIA+ACQAEAAABgCQgFgDgCgCQg3gBAAACQAAAAACAB").p("ABTAEQAHACAUAJQAQAIAIAAQADAAAAgBQAAgBAAgBQgPgIgJgEQgPgIgPAE").p("AAwAnQAAAagFAzQAAAFAAAAQABABABABQAGgNACgKQAAgBAAgVQAAgVgCgSIgDAA").p("AB2BJQgRgHgKgSQgIgRgKgCQAFAEAIAVQALAVAQAAQADAAACgBQAAAAAAgB").p("AgmAwQgRAVgfA5IABACQAJgCAUggQATghAAgKQAAgEAAAAIgBAB").p("AguiEQAIARAKAlIADAAQABgEAAgFQAAgTgSgZQgBgBgBgBIgBAAIgBAB").p("AhIg2QgPgTgCgcQAAgagCgQQAAgCgBgDIgCAAQgCAOAAABIAAABQABANAFAbQAHAiAIAHQACgBABgC").p("AiBgrQADAFADAFQAIAIAOAGQARAHAMAAQAGAAgEgCIgCgEQgqgTgLgFQgDgBgBAA").p("AiAALQgKAGgGAEQgGAGgBADQAGgCAHgFQAPgIAWgPQgFAAgWAL").p("AgvAUQgdAXgyAjQgoAcAAAAQAAAEAAABIAAAAQABAAABAAQAZgGAZgRQAKgHAKgIQAUgPAggiIgFgE").p("AgNBAQAAAHgDAOQAAAEAHAQQAFAMAFAEQADADADAAQAGAAgCgBQgCgDgCgDQgGgJgEgPQgCgGgGgXIgCAA").f("#fee17c").p("AAsgWQAAgQgNgKQgNgLgSAAQgSAAgOALQgNAKAAAQQAAAPANAJQAOALASAAQASAAANgLQANgJAAgP").f();
	this.shape.setTransform(18.3,16.5);

	// Warstwa 6
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("rgba(13,42,13,0.878)").p("AhtkiQBIB5B7G4QAEAJADALIARAAQgDgKgDgKQhDjggSg4QgTg8gfhPQgfhPgvg/").f();
	this.shape_1.setTransform(33.1,52.8);

	// Warstwa 5
	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#247b23").p("AEshrIgBAIIACgJQAAgBAAAAQAAABgBAB").p("AByElIAOAFIB4lhQg8BlglBwQgUA6gNA8QgCAJgCAI").p("ABpDhIgSA/QABgGAAgGQAJhzguhqQg1h+hjhhQAxBsArBoQAuByAnB2QAEALADALIAFAAIAAgBQAAAAAAAAIAAAAQAIgEAEgRQAFgSAAgh").p("ACQEqIAAAHQATgOAQgPQAnglAZgvQBGiEgOiYQgCCVhGCAQgdAzgsAoQgMALgNALIAPAA").f("#33b033").p("AEthsIgCAJIABgIQhrAugeBlQgdBngdBSQAAAhgFASQgEARgIAEIABABIA3AAIgPAAQANgLAMgLQAsgoAdgzQBGiAACiVQAAgCgBgDQABAAAAgBQACgDACgDIAAgEQgBAAgBAA").p("AB2EUQANg8AUg6QAlhwA8hlIh4FhIgOgFQACgIACgJ").p("AhsiuQAKBiAZBcQAnCRA7BzQAGAKAFALIAvABQgDgLgEgLQgnh2guhyQgrhogxhsQgDgDgEgD").p("ABYEpIAAABIABAAIgBgB").f("#ad4dad").p("Aj4kvQgKgCgWASQgUARgDAHQACABAFABQAyggAAgGQAAgDgBgBQgBABAAgB").f();
	this.shape_2.setTransform(34,52.3);

	// Warstwa 3
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("#4c8dee").p("AgaCiQB9iTgmjEQgeBugXBxQgSBXg8AwIAJAGQAXgGAMgP").f();
	this.shape_3.setTransform(39.5,116.4);

	// Warstwa 2
	this.shape_4 = new Shape();
	this.shape_4.graphics.f("#0066ff").p("Ag/jUQAGAUACAeQAAAIAAAqQAAAvgEAfQgEAWgLBIQgBAIgEAJQArAWAvgOQAwgOACgWQgDgOgBgPIAAhJQAAhJAIgmQAFgbAEgXQAPhSACgOQgIgChNgBQgWAAgTgBIgDAHIgDgHQgnABgVABQABAPAPAhQASAqADAIQAAABABAB").f("#247b23").p("Agpk6IADAHIADgHIgGAA").f("#0460e9").p("AALBVQgvAOgrgWQgMAbglAmQgEAEgEAEQg1A2AAAdQAAATAUATQApgXAwAFQAsgCApgKQAVgEAygRQAygRAAgVQgBgVADgHQgKgJgIgJQgYgXgLgVQgKgSgEgZQgCAWgwAO").f("#055ad9").p("AA3E3QAegDAdgGQAMgBALgGQAVgMAQgPQANgOADgVQACgNgJgLQgYgfgfgYQgDAHABAVQAAAVgyARQgyARgVAEQgpAKgsACQgwgFgpAXQAiAhAuAGQAxAIAvgEQAYgBAYgC").f();
	this.shape_4.setTransform(46.4,113.3);

	// Warstwa 7
	this.shape_5 = new Shape();
	this.shape_5.graphics.f("#472323").p("AijrSIACADQgBACgBADQgBABAAAAQgBgCgBgDIgDABIgHAjQgBAAgFgEQgBgBgBgBIgBAAQgDgBgDgDQgNgKgSAAQgFAAgEAEQAAgCAAgDIgCAAQgDAOAAABIAAABQAAAEgBAFQgBAMABANQgsgDgKADQgGACAAALQAAANANAOQAGAGANAKQgDgBAAAAQACAFADAEQgmAFgPAHQgOAGAAAMQAAAJATAHQAJAEATAGQgHAGgBADQAGgCAHgFQABAAAAAAIgDACQgUAPgLATQgLATAAARQgDARANAAQACAAAEgCIAAABQABAAACAAQAYgGAagRQgCANACASQAEAiAAAFIABABQABABAEAAQAFAAALgNQALgOAAAAQAAAnAcAAQAUAAARgbQAJgQAEgIQADADADAAQAHAAgDgCQgCgCgCgDQAEAEAKAHQAPAMAGAAQAHAAABgMQABgOAAgEQAAABANAKQAZA3AeBVQgdgmgjgiQgEgDgDgEQAKBiAZBeQAmCQA8ByQAFALAGAKIAHAAQgMAAgJABQABAPAPAhQASAqADAIQAAABABABQAHAUABAeQAAAIAAAqQAAAvgEAfQgEAWgLBJQgBAIgEAJQgMAbglAmQgEAEgDAEQg1A2AAAdQAAATAUATQAhAhAuAGQAxAIAwgEQAYgBAYgCQAegDAdgGQAMgBALgGQAVgMAQgPQANgOADgVQACgNgJgLQgYgfgfgYQgKgJgIgJQgYgXgLgVQgKgSgEgZQgDgOgBgPIAAhKQAAhJAIgmQAFgbAEgXQAPhSACgNQgHgDg2AAQANgLAMgLQAngkAZguQBGiFgOiYQgBgCAAgDQABgBAAAAQACgDACgDIAAgFQgBABgBAAQAAgBAAgBQgBABAAABQhsAugdBnQgeBngcBQIgMArQgCgHgCgGQADhmgphgQgYg4gggyQgOgqgUgzQgRgqgVglQAZAUALAAQAJAAABgIQAAgLAAgEQAAgSgFghQAgADALgDQAHgCAAgHQAAgDgKgTQgJgSgDgEIAEgBQAVgCAGgCQALgDAAgHQAAgIgRgPQgUgQgGgFQAHgEAMgHQAIgGAAgJQAAgHgKgCIgpAAIgUACIAAgBQAeg9AAgKQgBgEAAgDQAAgBgHAAQgaAAgWAMQgIAEgOALQABgXAAgLQABgVgTgBQgPALgKAUQgIgJgEgFQgGgHgHgDQAAgDgBAAQgCABgCgBQgBAAgBABQgCAAgDAA").f();
	this.shape_5.setTransform(32.3,72);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-0.7,-0.7,66.2,145.6);


(window.lpcad0701s.mc6 = function() {
	this.initialize();

	// Warstwa 6
	this.shape = new Shape();
	this.shape.graphics.f("#a9a954").p("AgniDIgDgQQgEANgDANQAoA7AaBOQAXBEAOA/QACgIACgHQAfigiAhn").f("#989842").p("Agxh5QgyCvCYBfIABgBIAAgBQgOg/gXhEQgahOgog7").f();
	this.shape.setTransform(49.1,35.4);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#a9a954").p("AAAiIIAAgPQgHAMgGALQAWBCAGBRQAEBFgCA/QAEgHADgHQBGiOheiD").f("#989842").p("AgNiAQhcCYB4CAIACgBQACg/gEhFQgGhRgWhC").f();
	this.shape_1.setTransform(32.6,35.1);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#989842").p("AhfigIgIgBQg8CnAagXIAXANQgIhYAZg4IAGAmIAHABIAAgsIgLgH").f();
	this.shape_2.setTransform(40.8,34);

	// Warstwa 5
	this.shape_3 = new Shape();
	this.shape_3.graphics.f("#efd097").p("AgPANQACACAAABIAGACQABAAAHAAQASAAAAgSQAAgTgSACQgSAEAAAQQAAAHACAD").f();
	this.shape_3.setTransform(13.5,25.1);

	// Warstwa 4
	this.shape_4 = new Shape();
	this.shape_4.graphics.f("#989842").p("AClCBQACgGAAgHQAAgEAAgEQgEgggghaQgTg0gUg2QgUALgZB2QgXBsAAAnQAAAJASgIQAfiYANhWQABACACACQACACABAAQAIAXAcBXQALAeAIAZQAIAcAGAUQACgGACgD").p("AhPicIAAAAQgXAsgiBlQgeBZAAAKQAAAIABADQABACACACQAYgkAihoQAPgwAHgcQAFAwAjDjIAMgEIAAAAIAAAAIAAgMQABAFAAAGQABgCAAgBQABgCAAgJQAAgWgvkZQgCABgDAD").f("#63c963").p("AgdCdQAAgGgBgFIAAAMQABgBAAAA").f();
	this.shape_4.setTransform(30.1,16.5);

	// Warstwa 2
	this.shape_5 = new Shape();
	this.shape_5.graphics.f("#e3a401").p("AiBlnQADAJAFAJQAGAJAIAKQgjAFgbAWQgMAJgJANQgJAOgHAPQAPADAOgCQAFgCAEgCQgsAogNA5QAwgTAfgsQgWA/AGBDQA2g4ALhKQgDAZAJAXQAHATAUAKQAUgpgBguQAAgngWgeQAdgCAPgWQAEgFAMgUQgNgMgSABQgLABgJAIQgKAIgJAJIgGgKIADgDQgHgXgJgXQgFgMgMgFIgLAGQgKARAFAU").f("#957764").p("AALhMQgIBYgtBjQgoBYAABhQAAANADAMQAFABAFACQDdBEBDizQgKg1gWgxQguhjgJhYQgIhWgHhLIhaAAQgGBKgKBX").f("#6d5444").p("Ag+FnQAXAhAlALICVAAQAlgLAXghQAUgbAAgkQAAgqgIgpQhDCzjdhEQgFgCgFgBQAFAVAMAR").f();
	this.shape_5.setTransform(22.6,55.9);

	// Warstwa 7
	this.shape_6 = new Shape();
	this.shape_6.graphics.f("#e3a401").p("ACkj6QgyCxCZBdIABgBIAAAAQACgJACgGQAeidh6hmQgJgegQgvQgSg0gVg2QgUALgZB3QgGAggFAZQgGgIgGgJIACgPQgCADgCADIAAgSIgKgIIgJgBQgYBDgJAkQgJhBgijUQgDABgCADIAAAAQgYAsgiBlQgNAngHAXQgGgVgJgVQgFgLgMgFIgLAGQgJARAFATQACAKAFAIQAGAKAIAJQgiAFgcAWQgMAKgJANQgIAOgIAPQAPADAPgDQAEgCAEgBQgsAogNA4QAwgTAfgrQgWA+AGBDQA2g4AMhKQgEAZAJAXQAHAUAUAKQAUgpAAgvQAAgmgWgeQAcgCAPgWQAEgGANgTQgOgNgSABQgLACgJAHQgCACgCACQAPgkASg4QAPgwAIgcQAEAwAiDfIgEAAQgGBKgJBWQgJBZgtBiQgpBYABBhQAAANACAMQAFAVAMASQAXAgAlAMICVAAQAlgMAXggQAUgcAAgkQAAgqgIgoQgKg1gWgyQguhjgJhYQAAgEgBgFQAvhtgxhlQAWhvAKhFQABABACADQACACABAAQAIAXAdBYQAFARAGAP").p("AAkkEQgMATgIASQAEgmAOgeIAEAbQgCACAAAC").f();
	this.shape_6.setTransform(27.7,48.3);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0,0.4,55.5,95.9);


(window.lpcad0701s.mc5 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#d75600").p("AG3gRQAKgGAIgFQAJgFAEgIQgSAZh2ATQgQADgSADQghAFgkACQhCAHhMACQgiABglAAQgDAAgEAAQgBAAgCAAIgIAAQAAAAgBAAQgBAAgBAAQhXAAhKgEQgDgBgCAAQgFAAgFAAQgMgBgMgBQg+gFg1gIQgEgBgEgBQgEAAgEgBQg4gIgigLQAKAEAJAHQAUANAjALQAjAJALAKQAIAHACAGQEtBBEuhBQACgGAIgHQAKgKAkgJQAjgLATgNQAKgHAKgF").f("#ff9900").p("AHXgrQACgEAAgEQAAgTgugPQgigLg7gKQhqgSiOgEQAAAAgBAAQgggBgiAAQgKAAgJAAQgZAAgZAAQijADh4AUQgsAHgfAIQgJADgIADQABAAgBAAQAAAAgBAAQguAQAAASQAAAEACAEQACAEAFAEQABACABAAQACACAEADQACAAABABIABAAQACABACABQAAABABAAQAMACALAGQAhALA5AIQAEABADAAQAEABAEABQA1AIA+AFQAMABAMABQAFAAAFAAQACAAADABQBKAEBXAAQABAAABAAQABAAAAAAIAIAAQACAAABAAQAEAAADAAQAlAAAigBQBMgCBCgHQAkgCAhgFQASgDAQgDQB2gTASgZQABgBAAgB").p("AFlgnQAAAEgDADQgLANgvALQgRADgWADQgNACgPACQg+AIhOADIhHABQgCAAgCAAQgIAAgHAAQgiAAgfgCQhXgDhEgLQhSgMgPgSQgDgDAAgEQAAgXBkgQQBLgMBhgDQAhgBAiAAQAjAAAgABQBhADBLAMQAqAHAYAHQAiAMAAAN").p("Amag9QgHgBgGABIgBgGQAEgCAAgCQAEABAGADIAAAG").p("AE1A6QAAAAAAgCQAAgCAAgDQkuBBkthBQAAADAAACQAAACAAAAQAAAIAFAHQAJAMANAJQAJAHAJAFQEGAxD7gxQAKgFAIgHQAMgJAKgMQAFgHAAgI").f("#b17751").p("AFDhAQgYgHgqgHQhLgMhhgDQgggBgjAAQgiAAghABQhhADhLAMQhkAQAAAXQAAAEADADQFZg6FHA6QADgDAAgEQAAgNgigM").f("#c28157").p("AEBgCQAWgDARgDQAvgLALgNQlHg6lZA6QAPASBSAMQBEALBXADQAfACAiAAQAHAAAIAAQACAAACAAIBHgBQBOgDA+gIQAPgCANgC").f("#ff9999").p("AmahDQgGgDgEgBQAAACgEACIABAGQAGgBAHABIAAgG").f("#ababab").p("AnPgjQAAACgBAAQAGADAGADQgBgBgCAAQgEgDgCgCQgBAAgBgC").f();
	this.shape.setTransform(44.1,14.8);

	// Warstwa 3
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#d75600").p("AG3gRQAKgGAIgFQAJgFAEgIQABgBAAgBQACgEAAgEQAAgTgugPQgigLg7gKQhqgSiOgEQAAAAgBAAQgggBgiAAQgKAAgJAAQgZAAgZAAQijADh4AUQgsAHgfAIQgJADgIADQABAAgBAAQAAAAgBAAQguAQAAASQAAAEACAEQACAEAFAEQAAACgBAAQAGADAGADIABAAQACABACABQAAABABAAQAMACALAGQAhALA5AIQAEABADAAQgEAAgEgBQg4gIgigLQAKAEAJAHQAUANAjALQAjAJALAKQAIAHACAGQAAADAAACQAAACAAAAQAAAIAFAHQAJAMANAJQAJAHAJAFQEGAxD7gxQAKgFAIgHQAMgJAKgMQAFgHAAgIQAAAAAAgCQAAgCAAgDQACgGAIgHQAKgKAkgJQAjgLATgNQAKgHAKgF").f();
	this.shape_1.setTransform(44.1,14.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-3.1,1.8,94.6,26);


(window.lpcad0701s.mc4 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#cccccc").p("AGegiQACgDAAgDQAAgah6gSQh6gSisAAQirAAh6ASQh6ASAAAaQAAADACADQACADAEAEQABAAAAAAQADACADACQADACAEABQAAABABAAQAKACAKAFQAdAIAyAHQAHAAAGABQAwAHA2ADQAKABAKABQAFAAAEABQADAAABAAQBCADBMABQACAAABAAIAGAAQACgBACABQBqgBBXgHQAfgCAegEQAPgDAPgBQBngPAPgVQABAAABgB").p("AANALQhZAAhAgKQg/gIAAgOQAAgOA/gKQBAgJBZAAQBZAAA/AJQBAAKAAAOQAAAOhAAIQg/AKhZAA").f("#a39d9d").p("AClABQBAgIAAgOQAAgOhAgKQg/gJhZAAQhZAAhAAJQg/AKAAAOQAAAOA/AIQBAAKBZAAQBZAAA/gK").p("AD3BKQAMgIAIgJQAFgGgBgFQAAgBAAgBQAAgBABgCQkKAzkJgzQABACAAABQAAABAAABQgBAFAFAGQAIAJALAIQAIAFAIAEQDmAnDdgnQAIgEAHgF").f("#8a8888").p("AGdggIgBgBQgPAVhnAPQgPABgPADQgeAEgfACQhXAHhqABQgCgBgCABIgGAAQgBAAgCAAQhMgBhCgDQgBAAgDAAQgEgBgFAAQgKgBgKgBQg2gDgwgHQgGAAgIgBQgxgHgegIQAJADAIAGQARAKAfAHQAfAIAKAIQAHAFABAGQEJAzEKgzQABgGAHgFQAJgIAggIQAfgHARgKQAIgGAJgEQAIgFAIgEQAIgEADgG").f("#ababab").p("AmXgbQAAABgBAAQAHAEAIACQgEgBgDgCQgDgCgDgCQAAAAgBAA").f();
	this.shape.setTransform(41.9,12);

	// Warstwa 3
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#cccccc").p("AGegiQACgDAAgDQAAgah6gSQh6gSisAAQirAAh6ASQh6ASAAAaQAAADACADQACADAEAEQAAABgBAAQAHAEAIACQAAABABAAQAKACAKAFQAdAIAyAHQAHAAAGABQgGAAgIgBQgxgHgegIQAJADAIAGQARAKAfAHQAfAIAKAIQAHAFABAGQABACAAABQAAABAAABQgBAFAFAGQAIAJALAIQAIAFAIAEQDmAnDdgnQAIgEAHgFQAMgIAIgJQAFgGgBgFQAAgBAAgBQAAgBABgCQABgGAHgFQAJgIAggIQAfgHARgKQAIgGAJgEQAIgFAIgEQAIgEADgGIgBgBQABAAABgB").f();
	this.shape_1.setTransform(41.9,12);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0.3,1.8,83.1,20.5);


(window.lpcad0701s.mc3 = function() {
	this.initialize();

	// Warstwa 3
	this.shape = new Shape();
	this.shape.graphics.f("#006600").p("AgRhpQgLAAgIADQgCABgBABQgBAAgBACIAAAAQgDADAAADQAAABABABQABAEAFADQAAAAABAAQAAABABAAQAHADALAAQAEAAAFgBQADAAAMgMQAAAAABAAQgBAAAAABQgHAJAAgBQADgBACgCQACgCABgCIAAAAQAAgBAAgBQAAgBAAgCIAAAAQgBgBAAgBIgBAAQgCgDgEgCQgHgDgKAA").f("#00cc00").p("AAHhhQAAAAABgBQgBABgBAAIABAA").p("AAIhfQAAAAAAAAIAAAAQAAAAAAAA").p("AAHhcQgMAMgDAAQgFABgEAAQgLAAgHgDIAfBrIAGAKIAQgCIAEgDIgCgFQgbg3AMg4QgCACgDABQAAABAHgJIAAgB").p("AgpiKQABgBABgBQgBgCgBgCIAAAG").f("#990000").p("ABVAzIAHADIAXAZIAFABQgEgJgEgIQgJgRgRgHQgTgHgVgCQAFgjAfgLQgoAAgKAnIgGgCIgGAEIACAFIgEADIgQACIgGgKIgKgDIgDAOQgsgVgrAiIgPALQAxggA1APIAPAMQgoAkgBA2IACABQgGgKAcgvQAlg/BIAbIgFgC").f();
	this.shape.setTransform(17.4,2.8);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#ff3232").p("ADZAuQAJgXAAgaQAAgMgBgLQgDgegOgaQgKgRgLgOQgTgYgagSQgigWgpABQgUAFgLADQgJgEgGgBQg0gRgoALQgoAMgNAOQgNAPgEALQgDALgJAJQgIAKgKADQgJAFgOAJQgNAKgJAfQgJAfAAAiQAAAhAQAbQAMAVAQARQAtASAtgKQAVgGAWgDQAtAsA6gVQAwgSAhgnIAkAPQARgNANgRQADgEAPgnIgMAhQAFgJAEgJ").p("ABuiDQAUAFANAKQANALgDAJQgCAJgQACQgRADgUgGQgLgCgIgFQgIgDgGgGQgOgKADgJQACgJARgDQAPgBAUAEQABABABAA").p("AAzA2QgRAQgYAAQgXAAgRgQQgRgQAAgYQAAgWARgPQARgRAXAAQAYAAARARQARAPAAAWQAAAYgRAQ").p("Ah2hHQAKAGAAAPQAAADAAACQgBAOgIAOQgKARgOAGQgIAFgHAAQgEAAgEgCQgKgGAAgQQgBgPAJgRQAKgQAOgIQAOgIAKAG").f("#fe7373").p("ABsiEQgUgEgPABQgRADgCAJQgDAJAOAKQAGAGAIADQAIAFALACQAUAGARgDQAQgCACgJQADgJgNgLQgNgKgUgFQgBAAgBgB").p("ABEAOQAAgWgRgPQgRgRgYAAQgXAAgRARQgRAPAAAWQAAAYARAQQARAQAXAAQAYAAARgQQARgQAAgY").p("AiOhFQgOAIgKAQQgJARABAPQAAAQAKAGQAEACAEAAQAHAAAIgFQAOgGAKgRQAIgOABgOQAAgCAAgDQAAgPgKgGQgKgGgOAI").f("#e51b1b").p("ADQBAIAMghQgPAngDAEQgNARgRANIgkgPQghAngwASQg6AVgtgsQgWADgVAGQgtAKgtgSQAUAVAYANQAlATAlgWQAMAKAOAIQAMAHAPACQAiAFAjgHQA2gPAjglIARAAQAEgCAEgCQAagQASg+QgEAJgFAJ").f();
	this.shape_1.setTransform(22,18);

	// Warstwa 4
	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#ff3232").p("Ag/jJQgLAAgIADQgCABAAABQgCABgBABIAAABQgCACAAADQAAABAAABQABAEAFADQAAAAABABQAAAAABAAIAQA2QgDABgDABQgoAMgNAOQgNAPgEAKQgDAMgJAJQgIAJgKAEQgJAEgOAKQgNAKgJAeQgJAeAAAkQAAAgAQAcQAMAVAQAQQAUAWAYAMQAlAUAlgWQAMAKAOAHQAMAIAPABQAiAGAjgIQA2gOAjgmIARAAQAEgBAEgDQAagPASg/QAJgXAAgaQAAgMgBgLQgDgegOgaQgKgRgLgNQgTgYgagSQgigWgpABQgUAEgLADQgJgDgGgCQgigLgdABQgEgbAGgcQADgBAAgCIAAgBQAAgBAAgBQAAgBAAgBQAAAAAAgBQAAAAAAABQAAgBgBgCQAAAAABgBQgBABAAAAQgCgCgFgDQgHgDgLAA").p("Agmi7QABAAAAgBQAAABgBAAIAAAA").p("AhXjpQABgBACgCQgCgBgBgCIAAAG").f();
	this.shape_2.setTransform(22,12.4);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-0.6,-11.6,45.2,48.1);


(window.lpcad0701s.mc2 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#af9797").p("AAykcQglgGgvgCQgbgBgfAAQg1AAgsAEQgZACgVADQgKACgJACQgoAJAAALQAAACABACQAHAJAgAGQAJACAKACQAVAEAZACQAsAEA1AAQAfAAAbgCQAvgCAlgGQAegFAPgGQAKgEAEgEQABgCAAgCQAAgHgPgGQgPgGgegF").p("AD8iLQgBABgBABQAKAYAAAhQAAALgBAHQgIAig0ApQgFAEgGAEQg8AygHAaIAFAAQAFgSBFg4QAPgMAMgLIACADQAegUAHgUQAAgBABgFQAKgSAAgXQAAgNgLgUQgDgPgIgIQgCAAgBAB").f("#cdb5b5").p("ACFikQgLAHgHAGIAAhqQgDABgDAAQgEAEgKAEIAAALIAAHxQAKgEAKgEIAAhmQAIAUAVAAQAIAAACgDQABgBAAgBQACABAAgNQAAgCgKgLQgKgMAAgCQAAgfAagXQALgLAtgZQAogXARgTQAageAAgsQAAhyhkAIQglADggAT").p("AD/iMQAIAIADAPQALAUAAANQAAAXgKASQgBAFAAABQgHAUgeAUIgCgDQgMALgPAMQhFA4gFASIgFAAQAHgaA8gyQgkAXgOARQgRASgGAWIAAjYQABAAAAAAQAMAAAdgaQAegaAXAAQAUAAAWAcQABgBACAA").p("AhcjjQg1AAgsgEIAAIDQBPAPBMgIIAAoIQgbACgfAA").p("AklkAQgDAAgEgBIAAH9QAXAJAXAHIAAn9QgggGgHgJ").f("#c4a9a9").p("AgijlIAAIIQBBgHBAgYIAAnxIgtAAQglAGgvAC").f("#c6a0a0").p("ABfjtIAAgLQgPAGgeAFIAtAA").f("#dec9c9").p("AjrjtQgKgCgJgCIAAH9QAhAKAgAGIAAoDQgZgCgVgE").f();
	this.shape.setTransform(30.1,25.8);

	// Warstwa 3
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#af9797").p("AAykcQglgGgvgCQgbgBgfAAQg1AAgsAEQgZACgVADQgKACgJACQgoAJAAALQAAACABACQgDAAgEgBIAAH9QAXAJAXAHQAhAKAgAGQBPAPBMgIQBBgHBAgYQAKgEAKgEIAAhmQAIAUAVAAQAIAAACgDQABgBAAgBQACABAAgNQAAgCgKgLQgKgMAAgCQAAgfAagXQALgLAtgZQAogXARgTQAageAAgsQAAhyhkAIQglADggATQgLAHgHAGIAAhqQgDABgDAAQABgCAAgCQAAgHgPgGQgPgGgegF").p("AD6iJQAKAYAAAhQAAALgBAHQgIAig0ApQgFAEgGAEQgkAXgOARQgRASgGAWIAAjYQABAAAAAAQAMAAAdgaQAegaAXAAQAUAAAWAcQgBABgBAB").f();
	this.shape_1.setTransform(30.1,25.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0,-3.5,60.3,58.9);


(window.lpcad0701s.mc1 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#a17d02").p("AGfA3IAAADQAAABACAPQABACABADQADAHAFADQACABADAAQAFAAADgHQACgFAAgGQAAgHgGgHQgJgJgKAFQgBAAAAAAQgBABAAAA").p("AlVjMIhPhUIgLAwIgKgJIBTBIIARgb").f("#e4af01").p("AGjBPQh1BIiKgUQiFgRh4g3QiLg9hVh9IgEAFIgIgCQAVBDAYAwQA+B6B1BEQCFBNCZgdQCRgZBghyIABgBQgFgDgDgH").f("#ffcc00").p("AGfA6IAAgDQiNAqiQgfQiMgch6hNQhwhIhhhdIgRAbQAQAWAUAbQADADACADIAEgFQBVB9CLA9QB4A3CFARQCKAUB1hIQgBgDgBgCQgCgPAAgB").f("#d3a301").p("AlFh8QgDBfApBVQBCCLCNA9QCLA8CSgvQCSgvBLiEQhgByiRAZQiZAdiFhNQh1hEg+h6QgYgwgVhD").f();
	this.shape.setTransform(42.1,25.4);

	// Warstwa 3
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#a17d02").p("AGfA3QiNAqiQgfQiMgch6hNQhwhIhhhdIhPhUIgLAwIgKgJIBTBIQAQAWAUAbQADADACADIgIgCQgDBfApBVQBCCLCNA9QCLA8CSgvQCSgvBLiEIABgBQACABADAAQAFAAADgHQACgFAAgGQAAgHgGgHQgJgJgKAFQgBAAAAAAQgBABAAAA").f();
	this.shape_1.setTransform(42.1,25.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-2,-3.4,88.5,57.9);


(window.lpcad0701s.obraz2 = function() {
	this.initialize();

	// Warstwa 2
	this.shape = new Shape();
	this.shape.graphics.f("#c28c3c").p("ARJ1cMgi6AAAMgAJAn/IAAAAIAACQIBnAAMAhSAAAMAAKgn+IAAAAIAAgoIAAhp").p("AOvyZMAAAAk8I9eAAIgxAAIADpdIgD8RIePAAIAAAy").f("#b4843e").p("AOvzLI+PAAIADcRIgDJdIAxAAIAAg2IAAonIAA7fIcmAAIA4AAIAAgy").f("#cda364").p("AN3yZIAAbfIAAInI8mAAIAAA2IdeAAMAAAgk8Ig4AA").f("rgba(255,255,204,0.988)").p("AN3yZI8mAAIAAbfIcmAAIAA7f").f("#e5e379").p("AN3JGI8mAAIAAInIcmAAIAAon").f("rgba(0,0,0,0.2)").p("ARJzzIAAAoIAAAAMgAKAn+MghSAAAIAAAqMAiOAAAMAAAgpQIgyAA").f();
	this.shape.setTransform(109.7,137.3);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-4.9,0,229.4,274.5);


(window.lpcad0701s.obraz1 = function() {
	this.initialize();

	// Warstwa 3
	this.shape = new Shape();
	this.shape.graphics.f("#c28c3c").p("ARiy2IAAiRMgi6AAAMgAJAn/IAAAAIAACQMAi5AAAMAAKgn+IAAAA").p("APIyEMAAAAk8I9eAAIgxAAIgcAAIAcgLIADpSIgD8RIePAAIAAAy").f("#b4843e").p("APIy2I+PAAIADcRIgDJSIAAALIAxAAIAAg3IAAomIAA7fIcmAAIA4AAIAAgy").f("#cda364").p("AOQyEIAAbfIAAImI8mAAIAAA3IdeAAMAAAgk8Ig4AA").f("#b6ac82").p("AOQyEI8mAAIAAbfIcmAAIAA7f").f("#83794e").p("AvHS4IAAgLIgcALIAcAA").p("AOQJbI8mAAIAAImIcmAAIAAom").f();
	this.shape.setTransform(107.2,135.2);

	// Warstwa 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.2)").p("AxGUpMAiOAAAMAAAgpQMgiOAAAMAAAApQ").f();
	this.shape_1.setTransform(114.9,142.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(-4.9,0,229.4,274.5);


(window.lpcad0701s.Symbol10 = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new Shape();
	this.shape.graphics.f("#96cee7").p("EA2tgjJMhtZAAAMAAAAtTMBtZAAAMAAAgtT").f("#46baee").p("EA2tAKKMhtZAAAIAAZAMBtZAAAIAA5A").f();
	this.shape.setTransform(350.1,225);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.nominalBounds = new Rectangle(0,0,700.2,450);